# Generated by Django 4.1 on 2022-09-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='es_leido',
            new_name='esLeido',
        ),
    ]
