# Generated by Django 4.1 on 2022-09-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0002_rename_es_leido_mensajes_esleido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='esLeido',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='titulo',
            field=models.CharField(default='Mensaje', max_length=40),
        ),
    ]
