# Generated by Django 4.1 on 2022-09-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0004_remove_mensajes_id_remove_mensajes_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='idmensaje',
            new_name='id_mensaje',
        ),
    ]
