# Generated by Django 4.1 on 2022-09-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0005_rename_idmensaje_mensajes_id_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
