# Generated by Django 4.1 on 2022-09-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0009_alter_enviarmensaje_destinatario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnviarMensaje',
        ),
    ]
