# Generated by Django 4.1 on 2022-09-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0012_mensaje_delete_enviarmensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateField(),
        ),
    ]
